-- Add a new column to sites to determine if reporting is enabled
ALTER TABLE SITE ADD COLUMN REPORTINGENABLED BOOLEAN;

-- Modify the attachments table for ticket attachement
ALTER TABLE ATTACHMENT DROP COLUMN `LINK`;
ALTER TABLE ATTACHMENT ADD COLUMN S3ID VARCHAR(255);
ALTER TABLE ATTACHMENT ADD COLUMN TITLE VARCHAR(255);
ALTER TABLE ATTACHMENT ADD COLUMN MIME VARCHAR(255);
ALTER TABLE ATTACHMENT ADD COLUMN UPLOADEPOCH INT(20);
ALTER TABLE ATTACHMENT MODIFY UPLOADEPOCH BIGINT;

-- Modify the comment table for ticket attachement
DROP TABLE COMMENT_ATTACHMENT;

-- Modify the ticket table for ticket attachement
CREATE TABLE `TICKET_ATTACHMENT` (
  `Ticket_ID` varchar(255) NOT NULL,
  `attachments_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`Ticket_ID`,`attachments_ID`),
  KEY `FK_TICKET_ATTACHMENT_attachments_ID` (`attachments_ID`),
  CONSTRAINT `FK_TICKET_ATTACHMENT_Ticket_ID` FOREIGN KEY (`Ticket_ID`) REFERENCES `TICKET` (`ID`),
  CONSTRAINT `FK_TICKET_ATTACHMENT_attachments_ID` FOREIGN KEY (`attachments_ID`) REFERENCES `ATTACHMENT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
